export const FETCH_COMPANIES_START = 'FETCH_COMPANIES_START';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_FAILED = 'FETCH_COMPANIES_FAILED';


export const FETCH_COMPANY_BY_ID_START = 'FETCH_COMPANY_BY_ID_START';
export const FETCH_COMPANY_BY_ID_SUCCESS = 'FETCH_COMPANY_BY_ID_SUCCESS';
export const FETCH_COMPANY_BY_ID_FAILED = 'FETCH_COMPANY_BY_ID_FAILED';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';